*: fix kernel config for module version magic
This commit changes forces emerge to use binary only packages rather
than compiling them from source. Without this option, packages are
compiled against the next available kernel version rather then the
current version. This sounds like a bug to file against the Container
Linux developer container. The result was that the modules were compiled
against the wronge kernel version and modprobe would refuse to load
them.

diff --git a/nvidia/compile b/nvidia/compile
--- a/nvidia/compile
+++ b/nvidia/compile
@@ -6,13 +6,15 @@ echo "Preparing environment"
 . /usr/share/coreos/release
 /usr/bin/emerge-gitclone
 git -C /var/lib/portage/coreos-overlay checkout "build-${COREOS_RELEASE_VERSION%%.*}"
-emerge -v coreos-sources
+emerge -gKq --jobs 4 --load-average 4 coreos-sources
 cp /lib/modules/*-coreos*/build/.config /usr/src/linux/.config
 KERNEL_VERSION=$(head -n 3 /usr/src/linux/.config | tail -n 1 | awk '{print $3}')
 make -C /usr/src/linux olddefconfig
 make -C /usr/src/linux modules_prepare
 
 echo "Compiling NVIDIA modules"
+mkdir -p /tmp/nvidia
+pushd /tmp/nvidia
 curl -Ls "http://us.download.nvidia.com/XFree86/Linux-x86_64/$DRIVER_VERSION/NVIDIA-Linux-x86_64-$DRIVER_VERSION.run" -o nvidia.run
 chmod +x nvidia.run
 ./nvidia.run -x -s
@@ -22,7 +24,7 @@ if echo "$KERNEL_VERSION" | grep -q "^4.10]" && [ "$DRIVER_VERSION" == "381.22" 
   patch -p1 < kernel_4.10.patch
 fi
 ./nvidia-installer -s -n --kernel-source-path=/usr/src/linux --no-check-for-alternate-installs --no-opengl-files --kernel-install-path="$PWD" --log-file-name="$PWD"/nvidia-installer.log || true
-if [ -e kernel/nvidia.ko ] ; then echo "Successfully compiled NVIDIA modules" ; else echo "Failed to compile NVIDIA modules" && exit 1 ; fi
+if [ -e kernel/nvidia.ko ] ; then echo "Successfully compiled NVIDIA modules" ; else echo "Failed to compile NVIDIA modules" && cat "$PWD"/nvidia-installer.log && exit 1 ; fi
 
 echo "Archiving assets"
 mkdir -p /out/lib /out/lib/modules/"$KERNEL_VERSION" /out/bin
